### ISSUE TITLE
Vagrant Snapshot List Errors

### ISSUE THREAD

**Issue by mattcdavis1** [Parallels/vagrant-parallels#291]
After saving a snapshot, running `vagrant snapshot list` generates an error

```
vagrant snapshot list
/Users/mattdavis/.vagrant.d/gems/2.2.5/gems/vagrant-parallels-1.7.2/lib/vagrant-parallels/driver/base.rb:334:in `list_snapshots': uninitialized constant VagrantPlugins::Parallels::Driver::Base::Nokogiri (NameError)
	from /Users/mattdavis/.vagrant.d/gems/2.2.5/gems/vagrant-parallels-1.7.2/lib/vagrant-parallels/cap.rb:58:in `snapshot_list'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/capability_host.rb:111:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/capability_host.rb:111:in `capability'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/snapshot/command/list.rb:29:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:235:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:229:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:229:in `with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/snapshot/command/list.rb:18:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/snapshot/command/root.rb:61:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:308:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/bin/vagrant:127:in `<main>'
```

**Comment by legal90** [comment]
Thanks for pointing on this! 
The fix has been released in [v1.7.3](https://github.com/Parallels/vagrant-parallels/releases/tag/v1.7.3)
