### ISSUE TITLE
What about Parallels Desktop 13?

### ISSUE THREAD

**Issue by salvis** [Parallels/vagrant-parallels#316]
https://parallels.github.io/vagrant-parallels/ lists only versions 10, 11, and 12.

Given that
https://forum.parallels.com/threads/parallels-13-and-vagrant-problem.342180/
has never received any reply, I'm wondering...

**Comment by tuminoid** [comment]
PR13 works for me, but it spams a lot. `vagrant-parallels` version is `1.7.7`

```
Bringing machine 'kisakone' up with 'parallels' provider...
==> kisakone: Registering VM image from the base box 'parallels/ubuntu-14.04'...
/Users/tumi/.vagrant.d/gems/2.4.2/gems/vagrant-parallels-1.7.7/lib/vagrant-parallels/action/box_register.rb:124:in `register_box': VagrantPlugins::Parallels::Driver::Meta#execute_prlctl at /opt/vagrant/embedded/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method VagrantPlugins::Parallels::Driver::PD_12#execute_prlctl
==> kisakone: Creating new virtual machine as a linked clone...
==> kisakone: Unregistering the box VM image...
==> kisakone: Setting the default configuration for VM...
/Users/tumi/.vagrant.d/gems/2.4.2/gems/vagrant-parallels-1.7.7/lib/vagrant-parallels/action/sane_defaults.rb:23:in `block in call': VagrantPlugins::Parallels::Driver::Meta#execute_prlctl at /opt/vagrant/embedded/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method VagrantPlugins::Parallels::Driver::PD_12#execute_prlctl
/Users/tumi/.vagrant.d/gems/2.4.2/gems/vagrant-parallels-1.7.7/lib/vagrant-parallels/action/sane_defaults.rb:23:in `block in call': VagrantPlugins::Parallels::Driver::Meta#execute_prlctl at /opt/vagrant/embedded/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method VagrantPlugins::Parallels::Driver::PD_12#execute_prlctl
/Users/tumi/.vagrant.d/gems/2.4.2/gems/vagrant-parallels-1.7.7/lib/vagrant-parallels/action/sane_defaults.rb:23:in `block in call': VagrantPlugins::Parallels::Driver::Meta#execute_prlctl at /opt/vagrant/embedded/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method VagrantPlugins::Parallels::Driver::PD_12#execute_prlctl
/Users/tumi/.vagrant.d/gems/2.4.2/gems/vagrant-parallels-1.7.7/lib/vagrant-parallels/action/sane_defaults.rb:23:in `block in call': VagrantPlugins::Parallels::Driver::Meta#execute_prlctl at /opt/vagrant/embedded/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method VagrantPlugins::Parallels::Driver::PD_12#execute_prlctl
/Users/tumi/.vagrant.d/gems/2.4.2/gems/vagrant-parallels-1.7.7/lib/vagrant-parallels/action/sane_defaults.rb:23:in `block in call': VagrantPlugins::Parallels::Driver::Meta#execute_prlctl at /opt/vagrant/embedded/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method VagrantPlugins::Parallels::Driver::PD_12#execute_prlctl
/Users/tumi/.vagrant.d/gems/2.4.2/gems/vagrant-parallels-1.7.7/lib/vagrant-parallels/action/sane_defaults.rb:23:in `block in call': VagrantPlugins::Parallels::Driver::Meta#execute_prlctl at /opt/vagrant/embedded/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method VagrantPlugins::Parallels::Driver::PD_12#execute_prlctl
/Users/tumi/.vagrant.d/gems/2.4.2/gems/vagrant-parallels-1.7.7/lib/vagrant-parallels/action/sane_defaults.rb:23:in `block in call': VagrantPlugins::Parallels::Driver::Meta#execute_prlctl at /opt/vagrant/embedded/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method VagrantPlugins::Parallels::Driver::PD_12#execute_prlctl
/Users/tumi/.vagrant.d/gems/2.4.2/gems/vagrant-parallels-1.7.7/lib/vagrant-parallels/action/sane_defaults.rb:23:in `block in call': VagrantPlugins::Parallels::Driver::Meta#execute_prlctl at /opt/vagrant/embedded/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method VagrantPlugins::Parallels::Driver::PD_12#execute_prlctl
/Users/tumi/.vagrant.d/gems/2.4.2/gems/vagrant-parallels-1.7.7/lib/vagrant-parallels/action/sane_defaults.rb:23:in `block in call': VagrantPlugins::Parallels::Driver::Meta#execute_prlctl at /opt/vagrant/embedded/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method VagrantPlugins::Parallels::Driver::PD_12#execute_prlctl
/Users/tumi/.vagrant.d/gems/2.4.2/gems/vagrant-parallels-1.7.7/lib/vagrant-parallels/action/sane_defaults.rb:23:in `block in call': VagrantPlugins::Parallels::Driver::Meta#execute_prlctl at /opt/vagrant/embedded/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method VagrantPlugins::Parallels::Driver::PD_12#execute_prlctl
/Users/tumi/.vagrant.d/gems/2.4.2/gems/vagrant-parallels-1.7.7/lib/vagrant-parallels/action/sane_defaults.rb:23:in `block in call': VagrantPlugins::Parallels::Driver::Meta#execute_prlctl at /opt/vagrant/embedded/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method VagrantPlugins::Parallels::Driver::PD_12#execute_prlctl
/Users/tumi/.vagrant.d/gems/2.4.2/gems/vagrant-parallels-1.7.7/lib/vagrant-parallels/action/sane_defaults.rb:23:in `block in call': VagrantPlugins::Parallels::Driver::Meta#execute_prlctl at /opt/vagrant/embedded/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method VagrantPlugins::Parallels::Driver::PD_12#execute_prlctl
/Users/tumi/.vagrant.d/gems/2.4.2/gems/vagrant-parallels-1.7.7/lib/vagrant-parallels/action/sane_defaults.rb:23:in `block in call': VagrantPlugins::Parallels::Driver::Meta#execute_prlctl at /opt/vagrant/embedded/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method VagrantPlugins::Parallels::Driver::PD_12#execute_prlctl
/Users/tumi/.vagrant.d/gems/2.4.2/gems/vagrant-parallels-1.7.7/lib/vagrant-parallels/action/sane_defaults.rb:23:in `block in call': VagrantPlugins::Parallels::Driver::Meta#execute_prlctl at /opt/vagrant/embedded/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method VagrantPlugins::Parallels::Driver::PD_12#execute_prlctl
/Users/tumi/.vagrant.d/gems/2.4.2/gems/vagrant-parallels-1.7.7/lib/vagrant-parallels/action/sane_defaults.rb:23:in `block in call': VagrantPlugins::Parallels::Driver::Meta#execute_prlctl at /opt/vagrant/embedded/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method VagrantPlugins::Parallels::Driver::PD_12#execute_prlctl
==> kisakone: Checking if box 'parallels/ubuntu-14.04' is up to date...
==> kisakone: Setting the name of the VM: kisakone-dev_kisakone_1514797490258_8118
==> kisakone: Clearing any previously set network interfaces...
==> kisakone: Forwarding ports...
    kisakone: 8080 => 8080
==> kisakone: Running 'pre-boot' VM customizations...
/Users/tumi/.vagrant.d/gems/2.4.2/gems/vagrant-parallels-1.7.7/lib/vagrant-parallels/action/customize.rb:29:in `block in call': VagrantPlugins::Parallels::Driver::Meta#execute_prlctl at /opt/vagrant/embedded/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method VagrantPlugins::Parallels::Driver::PD_12#execute_prlctl
/Users/tumi/.vagrant.d/gems/2.4.2/gems/vagrant-parallels-1.7.7/lib/vagrant-parallels/action/customize.rb:29:in `block in call': VagrantPlugins::Parallels::Driver::Meta#execute_prlctl at /opt/vagrant/embedded/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method VagrantPlugins::Parallels::Driver::PD_12#execute_prlctl
/Users/tumi/.vagrant.d/gems/2.4.2/gems/vagrant-parallels-1.7.7/lib/vagrant-parallels/action/customize.rb:29:in `block in call': VagrantPlugins::Parallels::Driver::Meta#execute_prlctl at /opt/vagrant/embedded/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method VagrantPlugins::Parallels::Driver::PD_12#execute_prlctl
```

**Comment by legal90** [comment]
@salvis Yes, Parallels Desktop 13 is supported. I'll update the information on the web page soon.
Regarding your issue - please, try to reinstall Vagrant and install the plugin once again. If the error still exists,  please post the output here together with the output of `vagrant plugin list`

@tuminoid The issue you've mentioned was fixed in vagrant-parallels `v1.7.8`
https://github.com/Parallels/vagrant-parallels/issues/311

**Comment by tuminoid** [comment]
Thanks, @legal90.

**Comment by salvis** [comment]
Thanks, both!
