### ISSUE TITLE
nokogiri dependency issue in latest vagrant

### ISSUE THREAD

**Issue by mcginty** [Parallels/vagrant-parallels#321]
This issue just came up when I upgraded my vagrant to 2.0.3 today.

```
~/vagrant/debian $ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.13.4
BuildVersion:   17E199

~/vagrant/debian $ vagrant version
Installed Version: 2.0.3

~/vagrant/debian $ vagrant plugin list
vagrant-parallels (1.7.8)

~/vagrant/debian $ vagrant init bento/debian-9
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.

~/vagrant/debian $ vagrant up
/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': incompatible library version - /Users/chihiro/.vagrant.d/gems/2.4.3/gems/nokogiri-1.8.2/lib/nokogiri/nokogiri.bundle (LoadError)
        from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/x/.vagrant.d/gems/2.4.3/gems/nokogiri-1.8.2/lib/nokogiri.rb:32:in `rescue in <top (required)>'
        from /Users/x/.vagrant.d/gems/2.4.3/gems/nokogiri-1.8.2/lib/nokogiri.rb:28:in `<top (required)>'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/x/.vagrant.d/gems/2.4.3/gems/vagrant-parallels-1.7.8/lib/vagrant-parallels/driver/base.rb:2:in `<top (required)>'
        from /Users/x/.vagrant.d/gems/2.4.3/gems/vagrant-parallels-1.7.8/lib/vagrant-parallels/driver/meta.rb:4:in `require_relative'
        from /Users/x/.vagrant.d/gems/2.4.3/gems/vagrant-parallels-1.7.8/lib/vagrant-parallels/driver/meta.rb:4:in `<top (required)>'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/x/.vagrant.d/gems/2.4.3/gems/vagrant-parallels-1.7.8/lib/vagrant-parallels/provider.rb:16:in `usable?'
        from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:340:in `block in default_provider'
        from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/registry.rb:49:in `block in each'
        from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/registry.rb:48:in `each'
        from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/registry.rb:48:in `each'
        from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:326:in `default_provider'
        from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/plugin/v2/command.rb:177:in `block in with_target_vms'
        from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/plugin/v2/command.rb:204:in `block in with_target_vms'
        from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/plugin/v2/command.rb:186:in `each'
        from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/plugin/v2/command.rb:186:in `with_target_vms'
        from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/plugins/commands/up/command.rb:87:in `execute'
        from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/cli.rb:46:in `execute'
        from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:269:in `cli'
        from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/bin/vagrant:151:in `<main>'
```

**Comment by romankulikov** [comment]
I cannot reproduce this problem.

**Comment by mcginty** [comment]
Interesting. I just reverted to vagrant-2.0.2 and this issue doesn't happen, so it's something to do with the 2.0.2 - 2.0.3 diff. Anything else I can do to give more debug info?

**Comment by legal90** [comment]
@mcginty Please, try to install Vagarnt v2.0.3 back and then repair plugins:
```
vagrant plugin repair
```
If it doesn't help, then do an expunge, so plugins will be reinstalled from the scratch:
```
vagrant plugin expunge --reinstall
```
https://www.vagrantup.com/docs/cli/plugin.html

**Comment by mcginty** [comment]
`vagrant plugin repair` worked for me after I re-upgraded to 2.0.3. Thanks for the recommendation! It'd be nice if vagrant recommended that earlier instead of dumping a stacktrace, but I think this is their bug at that point and not yours ;).
