### ISSUE TITLE
i can't import a base box

### ISSUE THREAD

**Issue by mtuktarov** [Parallels/vagrant-parallels#345]
Hi there I can't import a base box that has been created following this instruction 
http://parallels.github.io/vagrant-parallels/docs/boxes/base.html
I tried to reinstall parallels plugin and vagrant. 
Basebox available here:
http://kishmish.me/static/centos7.box

```
 0 mtuktarov@Marats-MacBook-Pro:~/repo/hello/vagrant(master *=)$ vagrant box add ./metadata.json 
==> box: Loading metadata for box './metadata.json'
    box: URL: file:///Users/mtuktarov/repo/hello/vagrant/metadata.json
==> box: Adding box 'centos7' (v0.1.0) for provider: parallels
    box: Unpacking necessary files from: file:///Users/mtuktarov/repo/hello/vagrant/centos7.box
/opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/box_collection.rb:144:in `block (4 levels) in add': undefined method `to_sym' for nil:NilClass (NoMethodError)
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/box_collection.rb:144:in `each'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/box_collection.rb:144:in `find'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/box_collection.rb:144:in `block (3 levels) in add'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/box_collection.rb:470:in `with_temp_dir'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/box_collection.rb:134:in `block (2 levels) in add'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/box_collection.rb:470:in `with_temp_dir'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/box_collection.rb:115:in `block in add'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/box_collection.rb:457:in `block in with_collection_lock'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/box_collection.rb:456:in `with_collection_lock'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/box_collection.rb:104:in `add'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/box_add.rb:357:in `box_add'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/box_add.rb:283:in `add_from_metadata'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/box_add.rb:118:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `run'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/commands/box/command/add.rb:78:in `execute'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/commands/box/command/root.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/cli.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/environment.rb:290:in `cli'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/bin/vagrant:182:in `<main>'
```

**Comment by legal90** [comment]
Hi @mtuktarov.
`metadata.json` in your box doesn't have this field, which is required:
```json
{
  "provider": "parallels"
}
```
See the box format documentation
https://www.vagrantup.com/docs/boxes/format.html#box-file

P.s.
You can check the content of your box by unpacking with tar (as it is just a usual gzip tarball):
```
tar xzvf ./centos7.box
```

**Comment by mtuktarov** [comment]
Your documentation is misleading then. I have providers field, there I have parallels provider

**Comment by legal90** [comment]
Yeah, docs looks a bit confusing. The "Box Metadata" section[here](https://www.vagrantup.com/docs/boxes/format.html#box-metadata) just describes the format for Vagrant private registries. 

It should not be confused with `metadata.json` file, which has to be included in each box file. Please change its content to 
```
{
  "provider": "parallels"
}
```
and then it should work.

**Comment by mtuktarov** [comment]
I confirm it helped
