### ISSUE TITLE
Can't work after upgrade to vagrant 2.2.7

### ISSUE THREAD

**Issue by fenbox** [Parallels/vagrant-parallels#346]
When I upgrade from 2.2.6 to 2.2.7, it can't boot and show the error message:
```
➜  vagrant-debian10-lemp git:(master) vagrant up
/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Users/fen/.vagrant.d/gems/2.4.9/gems/nokogiri-1.10.7/lib/nokogiri/nokogiri.bundle, 9): no suitable image found.  Did find: (LoadError)
	/Users/fen/.vagrant.d/gems/2.4.9/gems/nokogiri-1.10.7/lib/nokogiri/nokogiri.bundle: code signature in (/Users/fen/.vagrant.d/gems/2.4.9/gems/nokogiri-1.10.7/lib/nokogiri/nokogiri.bundle) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed. - /Users/fen/.vagrant.d/gems/2.4.9/gems/nokogiri-1.10.7/lib/nokogiri/nokogiri.bundle
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/fen/.vagrant.d/gems/2.4.9/gems/nokogiri-1.10.7/lib/nokogiri.rb:32:in `rescue in <top (required)>'
	from /Users/fen/.vagrant.d/gems/2.4.9/gems/nokogiri-1.10.7/lib/nokogiri.rb:28:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/fen/.vagrant.d/gems/2.4.9/gems/vagrant-parallels-2.0.1/lib/vagrant-parallels/driver/base.rb:2:in `<top (required)>'
	from /Users/fen/.vagrant.d/gems/2.4.9/gems/vagrant-parallels-2.0.1/lib/vagrant-parallels/driver/meta.rb:4:in `require_relative'
	from /Users/fen/.vagrant.d/gems/2.4.9/gems/vagrant-parallels-2.0.1/lib/vagrant-parallels/driver/meta.rb:4:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/fen/.vagrant.d/gems/2.4.9/gems/vagrant-parallels-2.0.1/lib/vagrant-parallels/provider.rb:16:in `usable?'
	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/environment.rb:361:in `block in default_provider'
	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/registry.rb:49:in `block in each'
	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/registry.rb:48:in `each'
	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/registry.rb:48:in `each'
	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/environment.rb:347:in `default_provider'
	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/environment.rb:943:in `guess_provider'
	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/environment.rb:955:in `find_configured_plugins'
	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/environment.rb:983:in `process_configured_plugins'
	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/environment.rb:178:in `initialize'
	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/bin/vagrant:145:in `new'
	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/bin/vagrant:145:in `<main>'
```

**Comment by legal90** [comment]
Hi! That was an issue of Vagrant 2.2.7 bundle:
https://github.com/hashicorp/vagrant/issues/11348#issuecomment-579471809

Vagrant 2.2.7 DMG installer has been recently rebuilt. Please, download and install it again.
https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.dmg

**Comment by silviopinheiro** [comment]
I have the same issue on windows version.
