### ISSUE TITLE
no suitable image found.  Did find: (LoadError)

### ISSUE THREAD

**Issue by krisballistiq** [Parallels/vagrant-parallels#347]
I have seen https://github.com/Parallels/vagrant-parallels/issues/346 which appears to be a similar issue and have subsequently deleted the .`vagrant.d` dir, uninstalled the old Vagrant, installed the new Vagrant package as directed and installed the `vagrant-parallels` plugin, however the problem persists (see below). Are there any local system issues that could be in play here, like ruby version etc?

Installed the recently rebuilt Vagrant from 
https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.dmg

Versions: 
- Vagrant 2.2.7
- vagrant-parallels-2.0.1
- Parallels Desktop 15 for mac, business edition 
- Mac OS 10.15.3
- ruby 2.6.3p62

Steps: 
```bash
vagrant plugin install vagrant-parallels
vagrant init parallels/ubuntu-14.04
vagrant up --provider parallels
```

Error: 
```
/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Users/myusername/.vagrant.d/gems/2.4.9/gems/nokogiri-1.10.7/lib/nokogiri/nokogiri.bundle, 9): no suitable image found.  Did find: (LoadError)
        /Users/myusername/.vagrant.d/gems/2.4.9/gems/nokogiri-1.10.7/lib/nokogiri/nokogiri.bundle: code signature in (/Users/myusername/.vagrant.d/gems/2.4.9/gems/nokogiri-1.10.7/lib/nokogiri/nokogiri.bundle) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed. - /Users/myusername/.vagrant.d/gems/2.4.9/gems/nokogiri-1.10.7/lib/nokogiri/nokogiri.bundle
        from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/myusername/.vagrant.d/gems/2.4.9/gems/nokogiri-1.10.7/lib/nokogiri.rb:32:in `rescue in <top (required)>'
        from /Users/myusername/.vagrant.d/gems/2.4.9/gems/nokogiri-1.10.7/lib/nokogiri.rb:28:in `<top (required)>'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/myusername/.vagrant.d/gems/2.4.9/gems/vagrant-parallels-2.0.1/lib/vagrant-parallels/driver/base.rb:2:in `<top (required)>'
        from /Users/myusername/.vagrant.d/gems/2.4.9/gems/vagrant-parallels-2.0.1/lib/vagrant-parallels/driver/meta.rb:4:in `require_relative'
        from /Users/myusername/.vagrant.d/gems/2.4.9/gems/vagrant-parallels-2.0.1/lib/vagrant-parallels/driver/meta.rb:4:in `<top (required)>'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/myusername/.vagrant.d/gems/2.4.9/gems/vagrant-parallels-2.0.1/lib/vagrant-parallels/provider.rb:16:in `usable?'
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/vagrantfile.rb:155:in `machine_config'
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/vagrantfile.rb:47:in `machine'
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/environment.rb:715:in `machine'
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/plugin/v2/command.rb:204:in `block in with_target_vms'
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/plugin/v2/command.rb:186:in `each'
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/plugin/v2/command.rb:186:in `with_target_vms'
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/plugins/commands/up/command.rb:87:in `execute'
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/cli.rb:66:in `execute'
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/environment.rb:290:in `cli'
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/bin/vagrant:182:in `<main>'
```

**Comment by krisballistiq** [comment]
I think this was my fault, i had virtualbox in a half installed state and forgot to set the VAGRANT_DEFAULT_PROVIDER var.
