### ISSUE TITLE
Test Suite fails with ArgumentError due to move to ruby3

### ISSUE THREAD

**Issue by jmfrank63** [Parallels/vagrant-parallels#395]
After checking out and running the test suite with `bundle exec rake` the seven test fail with an ArgumentError:

```
 1) VagrantPlugins::Parallels::Action::Network with private network with type dhcp creates a host-only interface with default IP and configures network in the guest
     Failure/Error: machine.config.vm.network 'private_network', network_args

     ArgumentError:
       wrong number of arguments (given 2, expected 1)
     # ./test/unit/action/network_test.rb:53:in `block (3 levels) in <top (required)>'

  2) VagrantPlugins::Parallels::Action::Network with private network with type dhcp and defined network creates a host-only interface with dhcp and configures network in the guest
     Failure/Error: machine.config.vm.network 'private_network', network_args

     ArgumentError:
       wrong number of arguments (given 2, expected 1)
     # ./test/unit/action/network_test.rb:53:in `block (3 levels) in <top (required)>'

  3) VagrantPlugins::Parallels::Action::Network with private network with static ip creates a host only interface and configures network in the guest
     Failure/Error: machine.config.vm.network 'private_network', network_args

     ArgumentError:
       wrong number of arguments (given 2, expected 1)
     # ./test/unit/action/network_test.rb:53:in `block (3 levels) in <top (required)>'

  4) VagrantPlugins::Parallels::Action::Network with private network with static ip when the desired host-only network exists uses the existing host-only network
     Failure/Error: machine.config.vm.network 'private_network', network_args

     ArgumentError:
       wrong number of arguments (given 2, expected 1)
     # ./test/unit/action/network_test.rb:53:in `block (3 levels) in <top (required)>'

  5) VagrantPlugins::Parallels::Action::Network with private network with static ipv6 creates a host-only interface with an IPv6 address <prefix>:1
     Failure/Error: machine.config.vm.network 'private_network', network_args

     ArgumentError:
       wrong number of arguments (given 2, expected 1)
     # ./test/unit/action/network_test.rb:53:in `block (3 levels) in <top (required)>'

  6) VagrantPlugins::Parallels::Action::Network with public network when bridge interface is specified and available bridges to the host interface and configures network in the guest
     Failure/Error: machine.config.vm.network 'public_network', network_args

     ArgumentError:
       wrong number of arguments (given 2, expected 1)
     # ./test/unit/action/network_test.rb:214:in `block (3 levels) in <top (required)>'

  7) VagrantPlugins::Parallels::Action::Network with public network when bridge interface should be chosen bridges to the host interface and configures network in the guest
     Failure/Error: machine.config.vm.network 'public_network', network_args

     ArgumentError:
       wrong number of arguments (given 2, expected 1)
     # ./test/unit/action/network_test.rb:214:in `block (3 levels) in <top (required)>'

Finished in 2.03 seconds (files took 0.37261 seconds to load)
72 examples, 7 failures, 1 pending
```

**Comment by legal90** [comment]
Fixed by https://github.com/Parallels/vagrant-parallels/pull/399
