### ISSUE TITLE
Vagrant doesn't use parallels as provider

### ISSUE THREAD

**Issue by GregOriol** [Parallels/vagrant-parallels#409]
Hi,

I have a strange issue with this plugin and parallels freshly installed on an M1 mac: vagrant doesn't seem to want to use parallels as the provider.

Here is what I'm getting in a new directory:
```
$ vagrant -v
Vagrant 2.2.18

$ vagrant plugin list
vagrant-disksize (0.1.3, global)
vagrant-hostmanager (1.8.9, global)
vagrant-parallels (2.2.4, global)

$ prlctl --version
prlctl version 17.1.0 (51516)

$ vagrant init bento/ubuntu-20.04
A `Vagrantfile` has been placed in this directory. You are now ready to `vagrant up` your first virtual environment! Please read the comments in the Vagrantfile as well as documentation on `vagrantup.com` for more information on using Vagrant.

$ vagrant up --provider=parallels
Bringing machine 'default' up with 'parallels' provider...
Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed. Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires this to be available on the PATH. If VirtualBox is installed, please find the `VBoxManage` binary and add it to the PATH environmental variable.
```

Could anyone have any idea on what is going on or what to look for to debug this?

**Comment by GregOriol** [comment]
It seems that VirtualBox is needed anyway: you must install it and then vagrant proceeds as expected with Parallels...

**Comment by legal90** [comment]
@GregOriol Actually, that is not a requirement.  If your vagrant configuration (`Vagrantfile`) don't have any reference to `virtualbox` provider, then it shouldn't fail like this even if you don't have Virtualbox installed

As I can see, you are using a blank `Vagrantfile`, which you got by `vagrant init bento/ubuntu-20.04`. 
So, the only guess I have is that you probably have the file `~/.vagrant.d/Vagrantfile` which Vagrant automatically merges into every other Vagrantfiles when it starts https://www.vagrantup.com/docs/vagrantfile#lookup-path

Otherwise, and if that's actually still interesting for you, I recommend checking the the debug output (`vagrant up --degug`) to find our why does it try to initialize the virtualbox provider.

**Comment by lorrin** [comment]
I can reproduce the behavior. I do not have a `~/.vagrant.d`.
```
❯ vagrant -v
Vagrant 2.2.19
❯ vagrant plugin list
vagrant-disksize (0.1.3, global)
vagrant-parallels (2.2.4, global)
❯ vagrant init bento/ubuntu-20.04
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
❯ vagrant up --provider=parallels
Bringing machine 'default' up with 'parallels' provider...
Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.
```

`--debug` yields a lot of output. Here's the last bit, hopefully that is enough to be helpful.

```
Bringing machine 'default' up with 'parallels' provider...
 INFO batch_action: Enabling parallelization by default.
 INFO batch_action: Disabling parallelization because only executing one action
 INFO batch_action: Batch action will parallelize: false
 INFO batch_action: Starting action: #<Vagrant::Machine:0x00007f96b01cb260> up {:destroy_on_error=>true, :install_provider=>false, :parallel=>true, :provision_ignore_sentinel=>false, :provision_types=>nil, :provider=>"parallels"}
 INFO machine: Calling action: up on provider Parallels (new VM)
DEBUG environment: Attempting to acquire process-lock: machine-action-04f76ffd0a0339eb6f4ec02c3c8a169e
DEBUG environment: Attempting to acquire process-lock: dotlock
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO environment: Acquired process lock: machine-action-04f76ffd0a0339eb6f4ec02c3c8a169e
 INFO interface: Machine: action ["up", "start", {:target=>:default}]
 INFO host: Autodetecting host type for [#<Vagrant::Environment: /Users/lorrin>]
DEBUG host: Trying: slackware
DEBUG host: Trying: freebsd
DEBUG host: Trying: void
DEBUG host: Trying: arch
DEBUG host: Trying: darwin
 INFO host: Detected: darwin!
 INFO runner: Running action: machine_action_up #<Vagrant::Action::Builder:0x00007f96af1f23c0>
 INFO base: VBoxManage path: VBoxManage
 INFO environment: Released process lock: machine-action-04f76ffd0a0339eb6f4ec02c3c8a169e
 INFO environment: Running hook: environment_unload
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00007f96b01c9640>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::VirtualBoxNotDetected: Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.>
ERROR vagrant: Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.
ERROR vagrant: /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/providers/virtualbox/driver/meta.rb:51:in `rescue in block in initialize'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/providers/virtualbox/driver/meta.rb:45:in `block in initialize'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/providers/virtualbox/driver/meta.rb:41:in `synchronize'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/providers/virtualbox/driver/meta.rb:41:in `initialize'
/Users/lorrin/.vagrant.d/gems/2.7.4/gems/vagrant-disksize-0.1.3/lib/vagrant/disksize/actions.rb:11:in `new'
/Users/lorrin/.vagrant.d/gems/2.7.4/gems/vagrant-disksize-0.1.3/lib/vagrant/disksize/actions.rb:11:in `<class:ResizeDisk>'
/Users/lorrin/.vagrant.d/gems/2.7.4/gems/vagrant-disksize-0.1.3/lib/vagrant/disksize/actions.rb:5:in `<class:Action>'
/Users/lorrin/.vagrant.d/gems/2.7.4/gems/vagrant-disksize-0.1.3/lib/vagrant/disksize/actions.rb:3:in `<module:Disksize>'
/Users/lorrin/.vagrant.d/gems/2.7.4/gems/vagrant-disksize-0.1.3/lib/vagrant/disksize/actions.rb:2:in `<module:Vagrant>'
/Users/lorrin/.vagrant.d/gems/2.7.4/gems/vagrant-disksize-0.1.3/lib/vagrant/disksize/actions.rb:1:in `<top (required)>'
/Users/lorrin/.vagrant.d/gems/2.7.4/gems/vagrant-disksize-0.1.3/lib/vagrant/disksize.rb:27:in `require_relative'
/Users/lorrin/.vagrant.d/gems/2.7.4/gems/vagrant-disksize-0.1.3/lib/vagrant/disksize.rb:27:in `block in <class:Plugin>'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:283:in `block in apply_action_name'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:282:in `each'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:282:in `apply_action_name'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:185:in `to_app'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:246:in `action_raw'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:215:in `block in action'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/environment.rb:614:in `lock'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `call'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `action'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
 INFO interface: error: Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.
Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.
 INFO interface: Machine: error-exit ["Vagrant::Errors::VirtualBoxNotDetected", "Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.\nVagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires\nthis to be available on the PATH. If VirtualBox is installed, please find the\n`VBoxManage` binary and add it to the PATH environmental variable."]
 ```

**Comment by lorrin** [comment]
For anyone trying the work-around of installing VirtualBox, note that the current installer aborts with _The installer has detected an unsupported architecture. VirtualBox only runs on the amd64 architecture._, but older [6.0.24 installer](https://www.virtualbox.org/wiki/Download_Old_Builds_6_0) has no such check.

**Comment by ferantivero** [comment]
if I am not mistaken is the `vagrant-disksize` plugin adding some noise here. I've just uninstalled that one and `vagrant up` started working back again.

**Comment by legal90** [comment]
Thank you, @ferantivero ! You're right, the issue seems to be caused by the `vagrant-disksize` plugin. It's well described here: https://github.com/sprotheroe/vagrant-disksize/issues/45

**Comment by AlekseyKorzun** [comment]
> For anyone trying the work-around of installing VirtualBox, note that the current installer aborts with _The installer has detected an unsupported architecture. VirtualBox only runs on the amd64 architecture._, but older [6.0.24 installer](https://www.virtualbox.org/wiki/Download_Old_Builds_6_0) has no such check.

Thanks, bruv 🙏🏼

**Comment by adriannaeguevarra** [comment]
> For anyone trying the work-around of installing VirtualBox, note that the current installer aborts with _The installer has detected an unsupported architecture. VirtualBox only runs on the amd64 architecture._, but older [6.0.24 installer](https://www.virtualbox.org/wiki/Download_Old_Builds_6_0) has no such check.

This solved my issue :)

**Comment by mplaats** [comment]
Just remove the machines in the .vagrant/machines folder if you can miss the data. There you find most of the time a reference to virtualbox. Offcourse first check out the contents :-)
